[project]
name="smarte_regelungen"
version="2025.1.0"
authors=[
	{name = "Alexander Göbel", email="alexander.goebel@uni-a.de"}
]
readme="README.md"
requires-python="~=3.13"
dependencies=[
	"av",
	"control",
	"gymnasium",
	"imageio>=2.37.1",
	"ipykernel",
	"jupyter",
	"jupyterlab",
	"keras",
	"matplotlib",
	"networkx",
	"notebook",
	"numpy",
	"pandas",
	"pillow",
	"pyb2d3>=0.7.4",
	"pyb2d3-sandbox",
	"pyb2d3-sandbox-ipycanvas",
	"pyb2d3-sandbox-jupyter",
	"pygame-ce",
	"scikit-fuzzy",
	"scikit-learn",
	"scipy",
	"sympy",
	"tensorflow",
	"tqdm",
	"transformers",
]

[project.optional-dependencies]
hub = [
	"jupyterhub"
]

[project.scripts]
smarte-regelungen = "jupyterlab.labapp:main"

[tool.uv.build-backend]
module-name = []

[tool.uv.sources]
pyb2d3-sandbox = { git = "https://github.com/derthorsten/pyb2d3.git", subdirectory = "companion_packages/pyb2d3_sandbox" }
pyb2d3-sandbox-ipycanvas = { git = "https://github.com/derthorsten/pyb2d3.git", subdirectory = "companion_packages/pyb2d3_sandbox_ipycanvas" }
pyb2d3-sandbox-jupyter = { git = "https://github.com/derthorsten/pyb2d3.git", subdirectory = "companion_packages/pyb2d3_sandbox_jupyter" }

[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"

